/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { User } from "firebase/auth";
export { User } from "firebase/auth";
export namespace Components {
    interface GoogleLoginButton {
    }
}
export interface GoogleLoginButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGoogleLoginButtonElement;
}
declare global {
    interface HTMLGoogleLoginButtonElement extends Components.GoogleLoginButton, HTMLStencilElement {
    }
    var HTMLGoogleLoginButtonElement: {
        prototype: HTMLGoogleLoginButtonElement;
        new (): HTMLGoogleLoginButtonElement;
    };
    interface HTMLElementTagNameMap {
        "google-login-button": HTMLGoogleLoginButtonElement;
    }
}
declare namespace LocalJSX {
    interface GoogleLoginButton {
        "onUserEmitted"?: (event: GoogleLoginButtonCustomEvent<User>) => void;
    }
    interface IntrinsicElements {
        "google-login-button": GoogleLoginButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "google-login-button": LocalJSX.GoogleLoginButton & JSXBase.HTMLAttributes<HTMLGoogleLoginButtonElement>;
        }
    }
}
